### ISSUE TITLE
T4: Make Responsive

### ISSUE THREAD

**Issue by hmzshin** [hmzshin/ecommerce#8]
In figma design there are also mobile views. **Mobile views** should be implemented to all 

- [x] Home
- [x] Shopping
- [x] Product
- [x] About
- [x] Team
- [x] Contac
    
- [x] [**CHECK Tailwind responsive solution:**](https://tailwindcss.com/docs/responsive-design)

**Comment by hmzshin** [comment]
Ürüne ait fotoğrafların gösterildiği galeri, Mozilla Firefox tarayıcısında beklenen şekilde çalışırken, Chromium tabanlı tarayıcılarda beklenen davranışı sergilemiyor.  @gokhanozdemir @erhanfirat

**Comment by gokhanozdemir** [comment]
Beklenen ve karşılaştığın davranışları resim video vs paylaşabilir misin?

**Comment by hmzshin** [comment]
@gokhanozdemir  Ekranın solunda Mozilla ve sağında Chrome tarayıcıları açık. Mozilla'da alttaki slider değişikliği takip ederken Chrome değişikliği takip etmiyor.

https://github.com/hmzshin/ecommerce/assets/59126754/b6512e77-a33c-481b-9f91-69a620bc1d40

**Comment by hmzshin** [comment]
@gokhanozdemir  
Slider oluşturmak için herhangi bir ek kütüphane kullanmadım. useRef React hook'u ve scrollIntoView JavaScript metodunu kullandım. Sorunla ilgili kodları [bu linkteki](https://github.com/hmzshin/ecommerce) 'develop' branch içerisinde yer alan Thumb componentında bulabilirsiniz. Teşekkürler.
